# Generated by Django 4.2.4 on 2024-06-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_animais_data_cad_anim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animais',
            name='idade_animal',
            field=models.CharField(max_length=30),
        ),
    ]
