# Generated by Django 4.2.4 on 2024-06-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_animais_idade_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animais',
            name='idade_animal',
            field=models.CharField(max_length=35),
        ),
    ]
